#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irFront,        sensorI2CCustom)
#pragma config(Sensor, S4,     irRight,        sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLiftL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLiftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mIntake,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sBackboard,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "HTIRS Driver.h"
#include "Core Library.c"

const int IR_THRESHOLD = 10;
#define filename "ir readings.txt"

TFileHandle irLogFile;

/**
 * Read the AC values of all receivers of the given IR sensor,
 * storing them as indexes 0 through 4 inclusive of the given
 * int array
 *
 * This saves the readings in the IR log file under the given
 * reading name.
 *
 * name must be four characters or less.
 */
void readIr(int irSensor, int* readings, const string name)
{
	HTIRS2readAllACStrength(irSensor, &readings[0], &readings[1], &readings[2], &readings[3], &readings[4]);

	TFileIOResult ioResult;
	WriteText(irLogFile, ioResult, "[");
	WriteText(irLogFile, ioResult, name);
	WriteText(irLogFile, ioResult, "]");
	for (int i = 0; i < 5; ++i) {
		WriteText(irLogFile, ioResult, " ");
		WriteLong(irLogFile, ioResult, readings[i]);
	}
	WriteText(irLogFile, ioResult, "\n");
}

/**
 * Returns true if the AC IR sensor receiver of the given direction is above IR_THRESHOLD
 *
 * Direction is 0 for farthest left, 4 for farthest right.
 */
bool isIrInDir(int irSensor, int receiverDir, const string name)
{
	int readings[5];
	readIr(irSensor, readings, name);
	const int value = readings[receiverDir];

	return value >= IR_THRESHOLD;
}

// Example of maximal-length recording:
// [turn] 111 111 111 111 111

task main()
{
	TFileIOResult ioResult;
	Delete(filename, ioResult);
	// 56 bytes for each recording, two recordings
	OpenWrite(irLogFile, ioResult, filename, (word) (27 * 2));

	servo[sHook] = HOOK_UP;
	servo[sBackboard] = BACKBOARD_MAX;
	nMotorEncoder[mLiftL] = 0;

	waitForStartWithDelay();

	prepareSlide();

	Forward(500, 20);
	Forward(3000, 35);

	wait10Msec(50);

	const bool goalPointingForward = isIrInDir(irFront, 2, "1st");

	Backward(500, 20);
	Backward(500, 35);

	if (!goalPointingForward) { // if goal is pointing horizontal or diagonal
		wait10Msec(50);
		// Turn 45 to get second reading
		Turn(1250, 35, 1);

		wait10Msec(50);
		const bool goalPointingDiagonal = isIrInDir(irFront, 3, "turn");

		if (!goalPointingDiagonal) { // if goal is pointing horizontal
			// Move at diagonal towards goal
			Forward(500, 20);
			Forward(4500, 35);

			// Turn 45
			wait10Msec(50);
			Turn(1150, 50, -1);

			// Move in line with goal
			wait10Msec(50);
			Forward(1000, 20);

			// Turn to face goal
			wait10Msec(50);
			Turn(2000, 50, -1);

			// Lift and go up to goal
			wait10Msec(50);
			liftSlide(LIFT_MAX);
			Forward(700, 20);
		} else { // if goal is pointing diagonal
			Forward(500, 20);
			Forward(2150, 35);

			wait10Msec(50);
			Turn(2450, 35, -1);

			liftSlide(LIFT_MAX);

			Forward(700, 20);
		}
	} else { // if goal is pointing forward
		wait10Msec(50);
		liftSlide(LIFT_MAX);

		Forward(1600, 20);
	}
	Close(file, ioResult);

	motor[mIntake] = -100;
	wait10Msec(200);
	motor[mIntake] = 0;

	Backward(1600, 20);

	liftSlide(LIFT_MIN);
}
