#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sMUX,           sensorI2CCustom)
#pragma config(Motor,  motorA,          mFlag,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "XanderDrivers/drivers/hitechnic-sensormux.h"
#include "XanderDrivers/drivers/hitechnic-irseeker-v2.h"
#include "XanderDrivers/drivers/lego-light.h"
#include "XanderDrivers/drivers/lego-ultrasound.h"
const tMUXSensor sensIR = msensor_S3_1;
const tMUXSensor sensBall = msensor_S3_2;
const tMUXSensor sensUS = msensor_S3_3;

#include "JoystickDriver.c"
#include "Core Library.c"

task main()
{
	homeServos();
	servo[sIR] = SERVO_IR_EDGE_1;

	tenseSlide();
	nMotorEncoder[mLiftR] = 0;

	waitForStartWithDelay();

	// Drive away from starting position along wall
	straight(DIR_FORWARD, 60, 1600);
	dispenseMomentum();

	int ac1, ac2, ac3, ac4, ac5;
	HTIRS2readAllACStrength(sensIR, ac1, ac2, ac3, ac4, ac5);

	if (ac3 <= 5) {
		// position 2 or 3

		servo[sIR] = SERVO_IR_EDGE_23;

		strafe(DIR_LEFT, 100, 1800);
		dispenseMomentum();

		wait10Msec(50);

		HTIRS2readAllACStrength(sensIR, ac1, ac2, ac3, ac4, ac5);
		servo[sIR] = SERVO_IR_FORWARD;

		if (ac3 <= 5) {
			// position 3

			nMotorEncoder[mFrontRight] = nMotorEncoder[mFrontLeft] = 0;
			yolodrive(60, 60, -100, 0);
			while (driveEncoderAverage() < 2600) {}
			yolodrive(0, 0, 0, 0);
			dispenseMomentum();

			rotate(DIR_CLOCKWISE, 60, 500);
			dispenseMomentum();
		} else {
			// position 2

			rotate(DIR_CLOCKWISE, 60, 600);
			dispenseMomentum();
		}
	} else {
		// position 1
	}

	// Rotate towards the IR
	lineupRotate();

	// Lift the floodgate so it doesn't get stuck on the ground
	raiseFloodgate();

	// Get close enough
	lineupDistance();
	dispenseMomentum();

	// Center onto the goal
	lineupLeftRight();
	dispenseMomentum();

	// Raise the slide
	liftSlide(LIFT_MAX);

	// Keep the lift from sliding
	motor[mLiftR] = motor[mLiftL] = 15;

	// Dispense the ball
	servo[sTongue] = TONGUE_DOWN;
	wait10Msec(35);

	jerk(DIR_FORWARD, 60, 150);
	wait10Msec(100);

	servo[sTongue] = TONGUE_UP;
	dispenseMomentum();

	// Lower the slide
	liftSlide(LIFT_MIN);
	tenseSlide();

	lineupKickstand();

	// Ram into the bar to knock it down
	straight(DIR_FORWARD, 100, 4800);
	dispenseMomentum();
}
