#pragma config(Sensor, S3,     sMUX,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "XanderDrivers/drivers/hitechnic-sensormux.h"
#include "XanderDrivers/drivers/hitechnic-irseeker-v2.h"
const tMUXSensor sensIR = msensor_S3_1;

task main()
{
	eraseDisplay();

	while (true) {
		int ac1, ac2, ac3, ac4, ac5;
		HTIRS2readAllACStrength(sensIR, ac1, ac2, ac3, ac4, ac5);

		nxtDisplayTextLine(4, "%02d %02d %02d %02d %02d", ac1, ac2, ac3, ac4, ac5);

		wait10Msec(1);
	}
}
