#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sensIR,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     mKnocker,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    sGrabber,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "JoystickDriver.c"
#include "HTIRS Driver.h"
#include "Core Library.c"

const int COUNT_THRESHOLD = 5;

task main()
{
	servo[sGrabber] = GRABBER_MIN;

	bDisplayDiagnostics = false;
	eraseDisplay();

	int pos = SERVO_IR_FORWARD;

	while (true) {
		servo[sIR] = pos;
		wait10Msec(25);

		int ac1, ac2, ac3, ac4, ac5;
		HTIRS2readAllACStrength(sensIR, ac1, ac2, ac3, ac4, ac5);

		int leftCount = 0;
		if (ac1 >= COUNT_THRESHOLD) ++leftCount;
		if (ac2 >= COUNT_THRESHOLD) ++leftCount;
		//if (ac3 >= COUNT_THRESHOLD) ++leftCount;

		int rightCount = 0;
		if (ac4 >= COUNT_THRESHOLD) ++rightCount;
		if (ac5 >= COUNT_THRESHOLD) ++rightCount;

		if (leftCount > rightCount) {
			pos -= 5;
		} else if (rightCount > leftCount) {
			pos += 5;
		}

		nxtDisplayTextLine(3, "%1d <> %1d", leftCount, rightCount);
	}
}
