#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sMUX,           sensorI2CCustom)
#pragma config(Sensor, S4,     sensUS,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     mKnocker,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "XanderDrivers/drivers/hitechnic-sensormux.h"
#include "XanderDrivers/drivers/hitechnic-irseeker-v2.h"
const tMUXSensor sensIR = msensor_S3_1;

#include "JoystickDriver.c"
#include "Core Library.c"

const bool fromLeft = true;

task main()
{
	int pos;
	if (fromLeft) {
		pos = SERVO_IR_FORWARD - 60;
	} else {
		pos = SERVO_IR_FORWARD + 100;
	}

	bDisplayDiagnostics = false;
	eraseDisplay();

	homeServos();

	while (true) {
		servo[sIR] = pos;
		nxtDisplayTextLine(3, "S: %03d", pos);

		wait10Msec(50);

		int ac1, ac2, ac3, ac4, ac5;
		HTIRS2readAllACStrength(sensIR, ac1, ac2, ac3, ac4, ac5);

		nxtDisplayTextLine(4, "%02d %02d %02d %02d %02d", ac1, ac2, ac3, ac4, ac5);

		if (fromLeft) {
			if (ac2 > 5 && ac3 <= 5) {
				break;
			}

			pos += 5;
		} else {
			if (ac4 > 5 && ac3 <= 5) {
				break;
			}

			pos -= 5;
		}
	}

	while (true) {}
}
