#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sMUX,           sensorI2CCustom)
#pragma config(Motor,  motorA,          mFlag,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "XanderDrivers/drivers/hitechnic-sensormux.h"
#include "XanderDrivers/drivers/hitechnic-irseeker-v2.h"
#include "XanderDrivers/drivers/lego-light.h"
#include "XanderDrivers/drivers/lego-ultrasound.h"
const tMUXSensor sensIR = msensor_S3_1;
const tMUXSensor sensBall = msensor_S3_2;
const tMUXSensor sensUS = msensor_S3_3;

#include "JoystickDriver.c"
#include "Core Library.c"

task main()
{
	nMotorEncoder[mLiftR] = 0;

	while (nNxtButtonPressed != kNoButton) {}
	while (true) {
		int lift = 0;
		if (nNxtButtonPressed == kRightButton) { // note that kRightButton != kButtonRight x(
			lift = 100;
		} else if (nNxtButtonPressed == kLeftButton) {
			lift = -50;
		} else if (nNxtButtonPressed == kEnterButton) {
			lift = 15;
		}

		motor[mLiftL] = motor[mLiftR] = lift;

		eraseDisplay();
		nxtDisplayTextLine(2, "%d", nMotorEncoder[mLiftR]);

		wait10Msec(10);
	}

	motor[mLiftL] = motor[mLiftR] = 0;
}
