#pragma config(Sensor, S3,     sMUX,           sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "XanderDrivers/drivers/hitechnic-sensormux.h"
#include "XanderDrivers/drivers/lego-light.h"
const tMUXSensor sensBall = msensor_S3_2;

task main()
{
	LSsetActive(sensBall);
	eraseDisplay();

	while (true) {
		nxtDisplayTextLine(1, "%03d", LSvalNorm(sensBall));
		wait10Msec(1);
	}
}
