#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLiftL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLiftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mIntake,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sTrapdoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Core Library.c"

task main()
{
	servo[sHook] = HOOK_UP;

	waitForStartWithDelay();

	nMotorEncoder[mLiftL] = 0;

	Forward(500, 20);
	Forward(500, 35);
	Forward(2000, 10);
	wait10Msec(50);
	prepareSlide();

	// Drive off the ramp
	Forward(3000, 35);

	// Drive to closest rolling goal
	Forward(3000, 35);

	// Grab the goal
	servo[sHook] = HOOK_DOWN;
	wait10Msec(50);

	Forward(1000, 35);

	// Turn back toward the rolling goal target zone
	Turn(1000, 35, -1);

	Backward(500, 20);
	Backward(8500, 35);

	Turn(500, 35, -1);
	Backward(500, 20);
	Backward(3500, 35);

	// Release the goal
	servo[sHook] = HOOK_UP;

	liftSlide(LIFT_MIN);
}
