#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sensIR,         sensorI2CCustom)
#pragma config(Sensor, S4,     sensUS,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     mKnocker,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "HTIRS Driver.h"
#include "Core Library.c"


task main()
{
	homeServos();
	tenseSlide();

	// Raise the floodgate
	servo[sFloodGate] = 5;
	wait10Msec(50);
	servo[sFloodGate] = 127;

	waitForStartWithDelay();

	// Drive down from ramp and toward rolling goals
	straight(DIR_FORWARD, 45, 3600);

	// Lower the floodgate
	servo[sFloodGate] = 250;
	wait10Msec(50);
	servo[sFloodGate] = 127;

	// Get some distance from the wall
	strafe(DIR_LEFT, 45, 300);
	dispenseMomentum();

	// Turn so we can back into the opposite corner
	rotate(DIR_CLOCKWISE, 45, 250);
	dispenseMomentum();

	// Back up into the opposite corner
	straight(DIR_BACKWARD, 80, 3540);
	dispenseMomentum();
}
