#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     sensIR,         sensorI2CCustom)
#pragma config(Sensor, S4,     sensUS,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     mKnocker,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int driveEncoderAverage()
{
	return (nMotorEncoder[mFrontLeft] + nMotorEncoder[mFrontRight]) / 2;
}

task main()
{
	const int POWER_INCREMENT = 5;
	const int DELAY = 100;

	int power = 0;

	eraseDisplay();

	int prevEnc = driveEncoderAverage();
	while (true) {
		motor[mFrontLeft] = motor[mFrontRight] = motor[mBackLeft] = motor[mBackRight] = power;

		wait1Msec(DELAY);

		int nowEnc = driveEncoderAverage();
		int distance = nowEnc - prevEnc;

		int rate = (int) ((float) distance * DELAY / 1000);

		nxtDisplayTextLine(3, "P: %2d%%", power);
		nxtDisplayTextLine(4, "D: %3d enc", distance);
		nxtDisplayTextLine(5, "R: %3d enc/s", rate);

		prevEnc = nowEnc;

		if (nNxtButtonPressed == kLeftButton) {
			power -= POWER_INCREMENT;
			if (power < 0) power = 0;
		} else if (nNxtButtonPressed == kRightButton) {
			power += POWER_INCREMENT;
			if (power > 100) power = 100;
		} else if (nNxtButtonPressed == kEnterButton) {
			break;
		}
	}

	motor[mFrontLeft] = motor[mFrontRight] = motor[mBackLeft] = motor[mBackRight] = 0;

	while (true) {}
}
