#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLiftL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLiftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mIntake,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sTrapdoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Core Library.c"

int intakeDir = 0;

void drive()
{
	int left = threshold(joystick.joy1_y1) * 100 / 128;
	int right = threshold(joystick.joy1_y2) * 100 / 128;

	if (joy1Btn(5)) { // left top shoulder
		left /= 2;
		right /= 2;
	}

	motor[mLeft] = left;
	motor[mRight] = right;
}

void lift()
{
	int power = threshold(joystick.joy2_y1) * 100 / 128;

	if (joy2Btn(11)) { // press left joystick
		nMotorEncoder[mLiftL] = 0;
	} else {
		// Go slower when going down
		if (power < 0) {
			power = power * 40 / 100;
		}

		bool tooLow = power < 0 && nMotorEncoder[mLiftL] <= LIFT_MIN;
		bool tooHigh = power > 0 && nMotorEncoder[mLiftL] >= LIFT_MAX;
		if (tooLow || tooHigh) {
			power = 0;
		}
	}

	if (joy2Btn(5)) { // left top shoulder
		power /= 3;
	}

	motor[mLiftL] = motor[mLiftR] = power;
}

void trapdoor()
{
	if (joystick.joy2_TopHat == 2) { // right button
		servo[sTrapdoor] = TRAPDOOR_OPEN;
	} else if (joystick.joy2_TopHat == 6) { // left button
		servo[sTrapdoor] = TRAPDOOR_CLOSED;
	}
}

void intake()
{
	if (joy2Btn(2)) { // up
		intakeDir = -1;
	} else if (joy2Btn(4)) { // down
		intakeDir = 1;
	} else if (joy2Btn(3)) { // right
		intakeDir = 0;
	}

	if (intakeDir == 0) {
		motor[mIntake] = threshold(joystick.joy2_y2) * 100 / 128;
	} else {
		motor[mIntake] = intakeDir * 100;
	}
}

void hook()
{
	if (joy1Btn(8)) { // left bottom shoulder button
		servo[sHook] = HOOK_DOWN;
	} else if (joy1Btn(6)) { // left top shoulder
		servo[sHook] = HOOK_UP;
	}
}

task main()
{
	nMotorEncoder[mLiftL] = 0;
	servo[sHook] = HOOK_UP;

	while(true) {
		if (!bDisconnected) {
			getJoystickSettings(joystick);

			drive();
			lift();
			intake();
			trapdoor();
			hook();
		} else {
			motor[mLeft] = motor[mRight] = motor[mLiftL] = motor[mLiftR] = motor[mIntake] = 0;
		}

		wait1Msec(100);
	}
}
