#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Ultra,          sensorSONAR)
#pragma config(Sensor, S3,     Ultra2,         sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLiftL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLiftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mIntake,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sTrapdoor,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Core Library.c"

const int TRAPDOOR_CLOSED = 128;
const int TRAPDOOR_OPEN = 25;

const int LIFT_MIN = 0;
const int LIFT_MAX = 7400;
const int LIFT_SLOW = 2100;

const int HOOK_DOWN = 255 / 4;
const int HOOK_UP = 255;

int intakeDir = 0;

void drive()
{
	motor[mLeft] = threshold(joystick.joy1_y1) * 100 / 128;
	motor[mRight] = threshold(joystick.joy1_y2) * 100 / 128;
}

void lift()
{
	int power = threshold(joystick.joy2_y1) * 100 / 128;

	if (joy2Btn(11)) { // press left joystick
		nMotorEncoder[mLiftL] = 0;
	} else {
		bool slowZone = power < 0 && nMotorEncoder[mLiftL] <= LIFT_SLOW;
		if (slowZone && power < -60) {
			power = -60;
		}

		bool tooLow = power < 0 && nMotorEncoder[mLiftL] <= LIFT_MIN;
		bool tooHigh = power > 0 && nMotorEncoder[mLiftL] >= LIFT_MAX;
		if (tooLow || tooHigh) {
			power = 0;
		}
	}

	motor[mLiftL] = motor[mLiftR] = power;
}

void trapdoor()
{
	if (joystick.joy2_TopHat == 2) { // right button
		servo[sTrapdoor] = TRAPDOOR_OPEN;
	} else if (joystick.joy2_TopHat == 6) { // left button
		servo[sTrapdoor] = TRAPDOOR_CLOSED;
	}
}

void intake()
{
	if (joy2Btn(2)) { // up
		intakeDir = -1;
	} else if (joy2Btn(4)) { // down
		intakeDir = 1;
	} else if (joy2Btn(3)) { // right
		intakeDir = 0;
	}

	if (intakeDir == 0) {
		motor[mIntake] = threshold(joystick.joy2_y2) * 100 / 128;
	} else {
		motor[mIntake] = intakeDir * 100;
	}
}

void hook()
{
	if (joy1Btn(5)) { // left shoulder button
		servo[sHook] = HOOK_DOWN;
	} else if (joy1Btn(6)) {
		servo[sHook] = HOOK_UP;
	}
}

task main()
{
	nMotorEncoder[mLiftL] = 0;
	servo[sHook] = HOOK_UP;

	while(true) {
		if (!bDisconnected) {
			getJoystickSettings(joystick);

			drive();
			lift();
			intake();
			trapdoor();
			hook();
		} else {
			motor[mLeft] = motor[mRight] = motor[mLiftL] = motor[mLiftR] = motor[mIntake] = 0;
		}

		wait1Msec(100);
	}
}
