#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     sensIR,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     mFrontLeft,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     mLiftR,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     mFrontRight,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     mKnocker,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     mLiftL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    sFloodGate,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    sIR,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    sTongue,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "HTIRS Driver.h"
#include "Core Library.c"

task main()
{
	bDisplayDiagnostics = false;
	eraseDisplay();

	while (nNxtButtonPressed != -1) {}
	while (nNxtButtonPressed == -1) {}

	nxtDisplayTextLine(3, "FL");
	motor[mFrontLeft] = 45;

	while (nNxtButtonPressed != -1) {}
	while (nNxtButtonPressed == -1) {}

	motor[mFrontLeft] = 0;
	nxtDisplayTextLine(3, "FR");
	motor[mFrontRight] = 45;

	while (nNxtButtonPressed != -1) {}
	while (nNxtButtonPressed == -1) {}

	motor[mFrontRight] = 0;
	nxtDisplayTextLine(3, "BL");
	motor[mBackLeft] = 45;

	while (nNxtButtonPressed != -1) {}
	while (nNxtButtonPressed == -1) {}

	motor[mBackLeft] = 0;
	nxtDisplayTextLine(3, "BR");
	motor[mBackRight] = 45;

	while (nNxtButtonPressed != -1) {}
	while (nNxtButtonPressed == -1) {}
}
