#pragma config(Sensor, S4,     sensUS,         sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	eraseDisplay();

	while (true) {
		int sensor = SensorValue[sensUS];
		nxtDisplayTextLine(3, "US: %03d", sensor);

		wait10Msec(1);
	}
}
