#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     mFrontRight,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     mBackRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     mFrontLeft,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     mBackLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     mIntake,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

/**
 * Set motor powers for yolonomic drive
 *
 * left and right: the tank drive values from -100 to 100.
 * strafe: the movement left and right from -100 to 100.
 * rotation: the rotation from -100 to 100.
 */
void yolodrive(int left, int right, int strafe, int rotation)
{
	int pFL = left + strafe + rotation;
	int pBL = left - strafe + rotation;
	int pFR = right - strafe - rotation;
	int pBR = right + strafe - rotation;

	float biggest = abs(pFL);
	if (abs(pBL) > biggest) biggest = abs(pBL);
	if (abs(pFR) > biggest) biggest = abs(pFR);
	if (abs(pBR) > biggest) biggest = abs(pBR);

	float scale = 1;
	if (biggest > 100) {
		scale = 100.0 / biggest;
	}

	motor[mFrontLeft] = (int) (scale * pFL);
	motor[mBackLeft] = (int) (scale * pBL);
	motor[mFrontRight] = (int) (scale * pFR);
	motor[mBackRight] = (int) (scale * pBR);
}

/**
 * Reset motor powers back to zero
 */
void resetDrive()
{
	motor[mFrontLeft] = motor[mBackLeft] = motor[mFrontRight] = motor[mBackRight] = 0;
}

int threshold(int raw)
{
	if (abs(raw) < 10) {
		return 0;
	} else {
		return raw * 100 / 128;
	}
}

task main()
{
	motor[mIntake] = 100;

	while (true) {
		getJoystickSettings(joystick);

		yolodrive(
				threshold(joystick.joy1_y1),
				threshold(joystick.joy1_y2),
				threshold(joystick.joy1_x1),
				threshold(joystick.joy1_x2)
				);
	}

/*
	wait10Msec(50);

	yolodrive(100, 100, 0, 0);
	wait10Msec(15);

	resetDrive();
	wait10Msec(15);

	yolodrive(-100, -100, 0, 0);
	wait10Msec(15);

	resetDrive();
	wait10Msec(15);

	yolodrive(0, 0, 100, 0);
	wait10Msec(15);

	resetDrive();
	wait10Msec(15);

	yolodrive(0, 0, -100, 0);
	wait10Msec(15);

	resetDrive();
	wait10Msec(15);

	yolodrive(0, 0, 0, 100);
	wait10Msec(50);

	resetDrive();
	wait10Msec(15);

	yolodrive(0, 0, 0, -100);
	wait10Msec(50);

	resetDrive();
	*/
}
