#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     irFront,        sensorI2CCustom)
#pragma config(Sensor, S4,     irRight,        sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     mLiftL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     mLeft,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     mLiftR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     mRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     mIntake,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    sHook,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    sBackboard,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "HTIRS Driver.h"
#include "Core Library.c"

task main()
{
	bDisplayDiagnostics = false;

	while (true) {
		int dir = HTIRS2readACDir(irRight);

		int dc1, dc2, dc3, dc4, dc5;
		HTIRS2readAllDCStrength(irRight, dc1, dc2, dc3, dc4, dc5);

		int ac1, ac2, ac3, ac4, ac5;
		HTIRS2readAllACStrength(irRight, ac1, ac2, ac3, ac4, ac5);

		eraseDisplay();
		nxtDisplayTextLine(2, "Dir: %d", dir);
		nxtDisplayTextLine(3, "1: DC %2d AC %2d", dc1, ac1);
		nxtDisplayTextLine(4, "2: DC %2d AC %2d", dc2, ac2);
		nxtDisplayTextLine(5, "3: DC %2d AC %2d", dc3, ac3);
		nxtDisplayTextLine(6, "4: DC %2d AC %2d", dc4, ac4);
		nxtDisplayTextLine(7, "5: DC %2d AC %2d", dc5, ac5);

		recordIrLog("irYolo.txt", irRight, ac1, ac2, ac3, ac4, ac5);

		wait10Msec(1);
	}
}
